databases:
- name: laravel_db
- name: metabase_db
- name: rails-db

services:
- name: laravel
  type: web
  repo: https://github.com/render-examples/php-laravel-docker
  env: docker
  envVars:
  - key: DB_CONNECTION
    value: pgsql
  - key: DATABASE_URL
    fromDatabase:
      name: laravel_db
      property: connectionString
  - key: APP_KEY
    value: some-secret-key-goes-here

- name: jekyll
  type: web
  repo: https://github.com/render-examples/jekyll
  env: static
  buildCommand: bundle exec jekyll build
  staticPublishPath: _site

- name: metabase
  type: web
  repo: https://github.com/render-examples/metabase
  env: docker
  envVars:
  - key: MB_DB_CONNECTION_URI
    fromDatabase:
      name: metabase_db
      property: connectionString

- name: rails
  type: web
  repo: https://github.com/render-examples/rails
  env: ruby
  buildCommand: ./build.sh
  startCommand: "bundle exec puma -t 5:5 ${PORT:-3000} -e ${RACK_ENV:-development}"
  envVars:
  - key: SECRET_KEY_BASE
    value: your-secret-here
  - key: DB_URL
    fromDatabase:
      name: rails-db
      property: connectionString
  - key: RAILS_SERVE_STATIC_FILES
    value: "true"

- name: rocket-example
  type: web
  repo: https://github.com/render-examples/rocket-rust-hello-world
  env: rust
  buildCommand: cargo build --release
  startCommand: cargo run --release
