services:
- name: elasticsearch-1
  type: web
  env: docker
  plan: standard
  envVars:
  - key: node.name
    fromService:
      name: elasticsearch-1
      type: web
      property: host
  - key: discovery.seed_hosts
    fromService:
      name: elasticsearch-1
      type: web
      property: host
  - key: cluster.initial_master_nodes
    fromService:
      name: elasticsearch-1
      type: web
      property: host
  disk:
    name: esdata
    mountPath: /usr/share/elasticsearch/data
- name: elasticsearch-2
  type: web
  branch: es-cluster
  env: docker
  plan: standard
  envVars:
  - key: node.name
    fromService:
      name: elasticsearch-2
      type: web
      property: host
  - key: discovery.seed_hosts
    fromService:
      name: elasticsearch-1
      type: web
      property: host
  - key: cluster.initial_master_nodes
    fromService:
      name: elasticsearch-1
      type: web
      property: host
  disk:
    name: esdata
    mountPath: /usr/share/elasticsearch/data
