databases:
- name: laravel_db
- name: metabase_db

services:
- name: laravel
  type: web
  repo: https://github.com/render-examples/php-laravel-docker
  env: docker
  envVars:
  - key: DB_CONNECTION
    value: pgsql
  - key: DATABASE_URL
    fromDatabase:
      name: laravel_db
      property: connectionString
  - key: APP_KEY
    value: some-secret-key-goes-here

- name: jekyll
  type: web
  repo: https://github.com/render-examples/jekyll
  env: static
  buildCommand: bundle exec jekyll build
  staticPublishPath: _site

- name: metabase
  type: web
  repo: https://github.com/render-examples/metabase
  env: docker
  envVars:
  - key: MB_DB_CONNECTION_URI
    fromDatabase:
      name: metabase_db
      property: connectionString
