databases:
- name: laravel_db

services:
- name: laravel
  type: web
  repo: https://github.com/render-examples/php-laravel-docker
  env: docker
  envVars:
  - key: DB_CONNECTION
    value: pgsql
  - key: DATABASE_URL
    fromDatabase:
      name: laravel_db
      property: connectionString
  - key: APP_KEY
    generateValue: true
